FROM python:3.8
RUN pip install tweepy
RUN pip install geopy
RUN pip install pymongo
RUN pip install kafka-python
RUN pip install python-dotenv
RUN apt-get update -y
RUN apt install docker.io -y
RUN pip install docker-compose

#Labels as key value pair
LABEL Maintainer="danish.99011"


# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /usr/app/src

#to COPY the remote file at working directory in container
COPY kafka_producer.py ./
COPY kafka_consumer.py ./
COPY country.py ./
COPY credentials.py ./
COPY kafka_details.py ./
COPY docker-compose.yml ./
COPY kafka_main.py ./
COPY .env ./
# Now the structure looks like this '/usr/app/src/test.py'


#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

# CMD [ "python", "./kafka_main.py"]
# CMD [ "python", "./kafka_consumer.py"]